package com.example.projecthub.settings

fun AppLanguage.t(key: String): String {
    return when (this) {
        AppLanguage.Portuguese -> portugueseStrings[key] ?: key
        AppLanguage.English -> englishStrings[key] ?: portugueseStrings[key] ?: key
        AppLanguage.Spanish -> spanishStrings[key] ?: portugueseStrings[key] ?: key
    }
}

private val portugueseStrings = mapOf(
    "login.subtitle" to "Iniciar sessão",
    "login.email" to "Email",
    "login.password" to "Palavra-passe",
    "login.submit" to "Entrar",
    "login.createAccount" to "Criar conta",
    "login.forgotPassword" to "Esqueci-me da palavra-passe",
    "login.resetTitle" to "Recuperar palavra-passe",
    "login.resetDescription" to "Indica o email associado a tua conta e vamos enviar-te um link para recuperares o acesso.",
    "login.resetSend" to "Enviar email",
    "login.invalidEmail" to "Insere um email válido, por exemplo nome@email.com.",
    "login.invalidForm" to "Preenche o email e uma palavra-passe com pelo menos 6 caracteres.",
    "register.subtitle" to "Criar conta",
    "register.name" to "Nome",
    "register.username" to "Username",
    "register.email" to "Email",
    "register.password" to "Palavra-passe",
    "register.submit" to "Registar",
    "register.haveAccount" to "Já tenho conta",
    "register.invalidEmail" to "Insere um email válido, por exemplo nome@email.com.",
    "register.invalidForm" to "Preenche todos os campos e usa uma palavra-passe com pelo menos 8 caracteres, letras e números.",
    "sidebar.dashboard" to "Dashboard",
    "sidebar.projects" to "Todos os Projetos",
    "sidebar.tasks" to "Todas as Tarefas",
    "sidebar.teams" to "Gestão de Equipas",
    "sidebar.reports" to "Relatórios Executivos",
    "sidebar.settings" to "Definições Globais",
    "sidebar.logout" to "Sair",
    "dashboard.title" to "Admin Dashboard",
    "dashboard.state" to "Estado da Dashboard",
    "dashboard.error" to "Erro",
    "dashboard.activeUsers" to "Utilizadores ativos",
    "dashboard.activeUsersDetail" to "Contas com estado ativo",
    "dashboard.completedProjects" to "Projetos concluídos",
    "dashboard.completedProjectsDetail" to "Total de projetos finalizados",
    "dashboard.pendingProjects" to "Projetos por concluir",
    "dashboard.pendingProjectsDetail" to "Projetos ainda não finalizados",
    "settings.title" to "Definições Globais",
    "settings.subtitle" to "Personaliza a experiência geral da aplicação",
    "settings.preferences" to "Preferências",
    "settings.language" to "Idioma",
    "settings.languageDescription" to "Define o idioma principal da interface.",
    "settings.theme" to "Tema",
    "settings.themeDescription" to "Escolhe a aparência geral do painel.",
    "settings.display" to "Visualização",
    "settings.dateFormat" to "Formato de data",
    "settings.dateFormatDescription" to "Exemplo:",
    "settings.notifications" to "Notificações",
    "settings.notificationsDescription" to "Recebe avisos visuais da aplicação.",
    "settings.sounds" to "Sons da aplicação",
    "settings.soundsDescription" to "Ativa feedback sonoro em ações principais.",
    "settings.testNotification" to "Enviar notificação de teste",
    "settings.testSound" to "Testar som",
    "settings.footer" to "Estas preferências ficam guardadas neste dispositivo e carregam automaticamente quando abres a app.",
    "theme.light" to "Claro",
    "theme.dark" to "Escuro",
    "theme.system" to "Sistema",
    "common.search" to "Pesquisa",
    "common.all" to "Todos",
    "common.allFemale" to "Todas",
    "common.cancel" to "Cancelar",
    "common.save" to "Guardar",
    "common.delete" to "Apagar",
    "common.confirm" to "Confirmar",
    "common.back" to "Voltar",
    "common.noDescription" to "Sem descrição",
    "common.total" to "Total",
    "common.pending" to "Pendentes",
    "common.completed" to "Completadas",
    "common.inProgress" to "Em progresso",
    "common.delayed" to "Atrasados",
    "projects.title" to "Todos os Projetos",
    "projects.add" to "Adicionar Projeto",
    "projects.list" to "Lista de Projetos",
    "projects.search" to "Pesquisar projetos...",
    "projects.deleteTitle" to "Apagar projeto",
    "projects.deleteQuestion" to "Tens a certeza que queres apagar",
    "projects.editTitle" to "Editar projeto",
    "projects.name" to "Nome",
    "projects.description" to "Descrição",
    "addProject.back" to "< Voltar aos Projetos",
    "addProject.title" to "Adicionar Novo Projeto",
    "addProject.name" to "Nome do Projeto",
    "addProject.namePlaceholder" to "Ex: Sistema CRM",
    "addProject.descriptionPlaceholder" to "Descreva os objetivos e âmbito do projeto...",
    "addProject.startDate" to "Data de Início",
    "addProject.endDate" to "Data de Fim (Prazo)",
    "addProject.manager" to "Gestor do Projeto",
    "addProject.managerPlaceholder" to "Selecione um gestor",
    "addProject.submit" to "Criar Projeto",
    "addTask.back" to "< Voltar às Tarefas",
    "addTask.title" to "Adicionar Nova Tarefa",
    "addTask.taskTitle" to "Título",
    "addTask.titlePlaceholder" to "Ex: Preparar documentação",
    "addTask.descriptionPlaceholder" to "Descreve o objetivo da tarefa...",
    "addTask.projectPlaceholder" to "Selecione um projeto",
    "addTask.submit" to "Criar Tarefa",
    "tasks.title" to "Todas as Tarefas",
    "tasks.subtitle" to "Tarefas organizadas por projeto",
    "tasks.add" to "Nova Tarefa",
    "tasks.search" to "Pesquisar por projeto ou tarefa...",
    "teams.title" to "Gestão de Equipas",
    "teams.subtitle" to "Administra utilizadores por função e projeto",
    "teams.totalUsers" to "Utilizadores totais",
    "teams.activeUsers" to "Utilizadores ativos",
    "teams.searchPlaceholder" to "Pesquisar por nome, username ou email...",
    "teams.role" to "Role",
    "teams.project" to "Projeto"
)

private val englishStrings = mapOf(
    "login.subtitle" to "Sign in",
    "login.password" to "Password",
    "login.submit" to "Sign in",
    "login.createAccount" to "Create account",
    "login.forgotPassword" to "Forgot password?",
    "login.resetTitle" to "Reset password",
    "login.resetDescription" to "Enter the email associated with your account and we will send you a recovery link.",
    "login.resetSend" to "Send email",
    "login.invalidEmail" to "Enter a valid email, for example name@email.com.",
    "login.invalidForm" to "Fill in your email and a password with at least 6 characters.",
    "register.subtitle" to "Create account",
    "register.name" to "Name",
    "register.password" to "Password",
    "register.submit" to "Register",
    "register.haveAccount" to "I already have an account",
    "register.invalidEmail" to "Enter a valid email, for example name@email.com.",
    "register.invalidForm" to "Fill in every field and use a password with at least 8 characters, letters and numbers.",
    "sidebar.projects" to "All Projects",
    "sidebar.tasks" to "All Tasks",
    "sidebar.teams" to "Team Management",
    "sidebar.reports" to "Executive Reports",
    "sidebar.settings" to "Global Settings",
    "sidebar.logout" to "Log out",
    "dashboard.state" to "Dashboard Status",
    "dashboard.error" to "Error",
    "dashboard.activeUsers" to "Active users",
    "dashboard.activeUsersDetail" to "Accounts with active status",
    "dashboard.completedProjects" to "Completed projects",
    "dashboard.completedProjectsDetail" to "Total finished projects",
    "dashboard.pendingProjects" to "Projects to finish",
    "dashboard.pendingProjectsDetail" to "Projects not finished yet",
    "settings.title" to "Global Settings",
    "settings.subtitle" to "Customize the app experience",
    "settings.preferences" to "Preferences",
    "settings.language" to "Language",
    "settings.languageDescription" to "Sets the main interface language.",
    "settings.theme" to "Theme",
    "settings.themeDescription" to "Chooses the dashboard appearance.",
    "settings.display" to "Display",
    "settings.dateFormat" to "Date format",
    "settings.dateFormatDescription" to "Example:",
    "settings.notifications" to "Notifications",
    "settings.notificationsDescription" to "Receive visual alerts from the app.",
    "settings.sounds" to "App sounds",
    "settings.soundsDescription" to "Enable sound feedback on main actions.",
    "settings.testNotification" to "Send test notification",
    "settings.testSound" to "Test sound",
    "settings.footer" to "These preferences are saved on this device and load automatically when you open the app.",
    "theme.light" to "Light",
    "theme.dark" to "Dark",
    "theme.system" to "System",
    "common.search" to "Search",
    "common.all" to "All",
    "common.allFemale" to "All",
    "common.cancel" to "Cancel",
    "common.save" to "Save",
    "common.delete" to "Delete",
    "common.confirm" to "Confirm",
    "common.back" to "Back",
    "common.noDescription" to "No description",
    "common.total" to "Total",
    "common.pending" to "Pending",
    "common.completed" to "Completed",
    "common.inProgress" to "In progress",
    "common.delayed" to "Delayed",
    "projects.title" to "All Projects",
    "projects.add" to "Add Project",
    "projects.list" to "Project List",
    "projects.search" to "Search projects...",
    "projects.deleteTitle" to "Delete project",
    "projects.deleteQuestion" to "Are you sure you want to delete",
    "projects.editTitle" to "Edit project",
    "projects.name" to "Name",
    "projects.description" to "Description",
    "addProject.back" to "< Back to Projects",
    "addProject.title" to "Add New Project",
    "addProject.name" to "Project Name",
    "addProject.namePlaceholder" to "Ex: CRM System",
    "addProject.descriptionPlaceholder" to "Describe the project goals and scope...",
    "addProject.startDate" to "Start Date",
    "addProject.endDate" to "End Date",
    "addProject.manager" to "Project Manager",
    "addProject.managerPlaceholder" to "Select a manager",
    "addProject.submit" to "Create Project",
    "addTask.back" to "< Back to Tasks",
    "addTask.title" to "Add New Task",
    "addTask.taskTitle" to "Title",
    "addTask.titlePlaceholder" to "Ex: Prepare documentation",
    "addTask.descriptionPlaceholder" to "Describe the task objective...",
    "addTask.projectPlaceholder" to "Select a project",
    "addTask.submit" to "Create Task",
    "tasks.title" to "All Tasks",
    "tasks.subtitle" to "Tasks organized by project",
    "tasks.add" to "New Task",
    "tasks.search" to "Search by project or task...",
    "teams.title" to "Team Management",
    "teams.subtitle" to "Manage users by role and project",
    "teams.totalUsers" to "Total users",
    "teams.activeUsers" to "Active users",
    "teams.searchPlaceholder" to "Search by name, username or email...",
    "teams.role" to "Role",
    "teams.project" to "Project"
)

private val spanishStrings = mapOf(
    "login.subtitle" to "Iniciar sesión",
    "login.password" to "Contraseña",
    "login.submit" to "Entrar",
    "login.createAccount" to "Crear cuenta",
    "login.forgotPassword" to "He olvidado mi contrasena",
    "login.resetTitle" to "Recuperar contrasena",
    "login.resetDescription" to "Introduce el email asociado a tu cuenta y te enviaremos un enlace de recuperacion.",
    "login.resetSend" to "Enviar email",
    "login.invalidEmail" to "Introduce un email válido, por ejemplo nombre@email.com.",
    "login.invalidForm" to "Rellena el email y una contraseña con al menos 6 caracteres.",
    "register.subtitle" to "Crear cuenta",
    "register.name" to "Nombre",
    "register.password" to "Contraseña",
    "register.submit" to "Registrar",
    "register.haveAccount" to "Ya tengo cuenta",
    "register.invalidEmail" to "Introduce un email válido, por ejemplo nombre@email.com.",
    "register.invalidForm" to "Rellena todos los campos y usa una contraseña con al menos 8 caracteres, letras y números.",
    "sidebar.dashboard" to "Panel",
    "sidebar.projects" to "Todos los Proyectos",
    "sidebar.tasks" to "Todas las Tareas",
    "sidebar.teams" to "Gestión de Equipos",
    "sidebar.reports" to "Informes Ejecutivos",
    "sidebar.settings" to "Ajustes Globales",
    "sidebar.logout" to "Salir",
    "dashboard.title" to "Panel Admin",
    "dashboard.state" to "Estado del panel",
    "dashboard.error" to "Error",
    "dashboard.activeUsers" to "Usuarios activos",
    "dashboard.activeUsersDetail" to "Cuentas con estado activo",
    "dashboard.completedProjects" to "Proyectos completados",
    "dashboard.completedProjectsDetail" to "Total de proyectos finalizados",
    "dashboard.pendingProjects" to "Proyectos por terminar",
    "dashboard.pendingProjectsDetail" to "Proyectos aún no finalizados",
    "settings.title" to "Ajustes Globales",
    "settings.subtitle" to "Personaliza la experiencia de la aplicación",
    "settings.preferences" to "Preferencias",
    "settings.language" to "Idioma",
    "settings.languageDescription" to "Define el idioma principal de la interfaz.",
    "settings.theme" to "Tema",
    "settings.themeDescription" to "Elige la apariencia general del panel.",
    "settings.display" to "Visualización",
    "settings.dateFormat" to "Formato de fecha",
    "settings.dateFormatDescription" to "Ejemplo:",
    "settings.notifications" to "Notificaciones",
    "settings.notificationsDescription" to "Recibe avisos visuales de la aplicación.",
    "settings.sounds" to "Sonidos de la aplicación",
    "settings.soundsDescription" to "Activa feedback sonoro en acciones principales.",
    "settings.testNotification" to "Enviar notificación de prueba",
    "settings.testSound" to "Probar sonido",
    "settings.footer" to "Estas preferencias se guardan en este dispositivo y cargan automáticamente al abrir la app.",
    "theme.light" to "Claro",
    "theme.dark" to "Oscuro",
    "theme.system" to "Sistema",
    "common.search" to "Búsqueda",
    "common.all" to "Todos",
    "common.allFemale" to "Todas",
    "common.cancel" to "Cancelar",
    "common.save" to "Guardar",
    "common.delete" to "Eliminar",
    "common.confirm" to "Confirmar",
    "common.back" to "Volver",
    "common.noDescription" to "Sin descripción",
    "common.total" to "Total",
    "common.pending" to "Pendientes",
    "common.completed" to "Completadas",
    "common.inProgress" to "En progreso",
    "common.delayed" to "Atrasados",
    "projects.title" to "Todos los Proyectos",
    "projects.add" to "Añadir Proyecto",
    "projects.list" to "Lista de Proyectos",
    "projects.search" to "Buscar proyectos...",
    "projects.deleteTitle" to "Eliminar proyecto",
    "projects.deleteQuestion" to "Seguro que quieres eliminar",
    "projects.editTitle" to "Editar proyecto",
    "projects.name" to "Nombre",
    "projects.description" to "Descripción",
    "addProject.back" to "< Volver a Proyectos",
    "addProject.title" to "Añadir Nuevo Proyecto",
    "addProject.name" to "Nombre del Proyecto",
    "addProject.namePlaceholder" to "Ej: Sistema CRM",
    "addProject.descriptionPlaceholder" to "Describe los objetivos y alcance del proyecto...",
    "addProject.startDate" to "Fecha de Inicio",
    "addProject.endDate" to "Fecha de Fin",
    "addProject.manager" to "Gestor del Proyecto",
    "addProject.managerPlaceholder" to "Selecciona un gestor",
    "addProject.submit" to "Crear Proyecto",
    "addTask.back" to "< Volver a Tareas",
    "addTask.title" to "Añadir Nueva Tarea",
    "addTask.taskTitle" to "Título",
    "addTask.titlePlaceholder" to "Ej: Preparar documentación",
    "addTask.descriptionPlaceholder" to "Describe el objetivo de la tarea...",
    "addTask.projectPlaceholder" to "Selecciona un proyecto",
    "addTask.submit" to "Crear Tarea",
    "tasks.title" to "Todas las Tareas",
    "tasks.subtitle" to "Tareas organizadas por proyecto",
    "tasks.add" to "Nueva Tarea",
    "tasks.search" to "Buscar por proyecto o tarea...",
    "teams.title" to "Gestión de Equipos",
    "teams.subtitle" to "Administra usuarios por rol y proyecto",
    "teams.totalUsers" to "Usuarios totales",
    "teams.activeUsers" to "Usuarios activos",
    "teams.searchPlaceholder" to "Buscar por nombre, username o email...",
    "teams.role" to "Rol",
    "teams.project" to "Proyecto"
)
