package com.example.projecthub.settings

fun AppLanguage.t(key: String): String {
    return when (this) {
        AppLanguage.Portuguese -> portugueseStrings[key] ?: key
        AppLanguage.English -> englishStrings[key] ?: portugueseStrings[key] ?: key
        AppLanguage.Spanish -> spanishStrings[key] ?: portugueseStrings[key] ?: key
    }
}

private val portugueseStrings = mapOf(
    "login.subtitle" to "Iniciar sessão",
    "login.email" to "Email",
    "login.password" to "Palavra-passe",
    "login.submit" to "Entrar",
    "login.createAccount" to "Criar conta",
    "login.forgotPassword" to "Esqueci-me da palavra-passe",
    "login.resetTitle" to "Recuperar palavra-passe",
    "login.resetDescription" to "Indica o email associado a tua conta e vamos enviar-te um link para recuperares o acesso.",
    "login.resetSend" to "Enviar email",
    "login.invalidEmail" to "Insere um email válido, por exemplo nome@email.com.",
    "login.invalidForm" to "Preenche o email e uma palavra-passe com pelo menos 6 caracteres.",
    "register.subtitle" to "Criar conta",
    "register.name" to "Nome",
    "register.username" to "Username",
    "register.email" to "Email",
    "register.password" to "Palavra-passe",
    "register.submit" to "Registar",
    "register.haveAccount" to "Já tenho conta",
    "register.invalidEmail" to "Insere um email válido, por exemplo nome@email.com.",
    "register.invalidForm" to "Preenche todos os campos e usa uma palavra-passe com pelo menos 8 caracteres, letras e números.",
    "sidebar.dashboard" to "Dashboard",
    "sidebar.projects" to "Todos os Projetos",
    "sidebar.tasks" to "Todas as Tarefas",
    "sidebar.teams" to "Gestão de Equipas",
    "sidebar.reports" to "Relatórios Executivos",
    "sidebar.settings" to "Definições",
    "sidebar.logout" to "Sair",
    "dashboard.title" to "Admin Dashboard",
    "dashboard.state" to "Estado da Dashboard",
    "dashboard.error" to "Erro",
    "dashboard.activeUsers" to "Utilizadores ativos",
    "dashboard.activeUsersDetail" to "Contas com estado ativo",
    "dashboard.completedProjects" to "Projetos concluídos",
    "dashboard.completedProjectsDetail" to "Total de projetos finalizados",
    "dashboard.pendingProjects" to "Projetos por concluir",
    "dashboard.pendingProjectsDetail" to "Projetos ainda não finalizados",
    "settings.title" to "Definições Globais",
    "settings.subtitle" to "Personaliza a experiência geral da aplicação",
    "settings.preferences" to "Preferências",
    "settings.language" to "Idioma",
    "settings.languageDescription" to "Define o idioma principal da interface.",
    "settings.theme" to "Tema",
    "settings.themeDescription" to "Escolhe a aparência geral do painel.",
    "settings.display" to "Visualização",
    "settings.dateFormat" to "Formato de data",
    "settings.dateFormatDescription" to "Exemplo:",
    "settings.notifications" to "Notificações",
    "settings.notificationsDescription" to "Recebe avisos visuais da aplicação.",
    "settings.sounds" to "Sons da aplicação",
    "settings.soundsDescription" to "Ativa feedback sonoro em ações principais.",
    "settings.testNotification" to "Enviar notificação de teste",
    "settings.testNotificationText" to "As notificações estão ativas.",
    "settings.testSound" to "Testar som",
    "settings.footer" to "Estas preferências ficam guardadas neste dispositivo e carregam automaticamente quando abres a app.",
    "theme.light" to "Claro",
    "theme.dark" to "Escuro",
    "theme.system" to "Sistema",
    "common.search" to "Pesquisa",
    "common.all" to "Todos",
    "common.allFemale" to "Todas",
    "common.cancel" to "Cancelar",
    "common.save" to "Guardar",
    "common.delete" to "Apagar",
    "common.confirm" to "Confirmar",
    "common.back" to "Voltar",
    "common.ok" to "OK",
    "common.retry" to "Tentar novamente",
    "common.moreInfo" to "Mais info",
    "common.exportCsv" to "Exportar CSV",
    "common.saving" to "A guardar...",
    "common.creating" to "A criar...",
    "common.create" to "Criar",
    "common.completing" to "A concluir...",
    "common.start" to "Início",
    "common.end" to "Fim",
    "common.deadline" to "Prazo",
    "common.status" to "Estado",
    "common.date" to "Data",
    "common.photos" to "Fotos",
    "common.noPhotos" to "Sem fotos",
    "common.photoEmpty" to "Esta observação não tem fotos anexadas.",
    "common.progress" to "Progresso",
    "common.rows" to "linhas",
    "common.users" to "Utilizadores",
    "common.user" to "Utilizador",
    "common.location" to "Local",
    "common.hours" to "Horas",
    "common.selectUser" to "Seleciona um utilizador",
    "common.noProjectUsers" to "Este projeto ainda não tem utilizadores associados.",
    "role.admin" to "Admin",
    "role.manager" to "Gestor",
    "role.user" to "Utilizador",
    "common.noDescription" to "Sem descrição",
    "common.total" to "Total",
    "common.pending" to "Pendentes",
    "common.completed" to "Concluídas",
    "common.inProgress" to "Em progresso",
    "common.delayed" to "Atrasadas",
    "projects.title" to "Todos os Projetos",
    "projects.add" to "Adicionar Projeto",
    "projects.list" to "Lista de Projetos",
    "projects.search" to "Pesquisar projetos...",
    "projects.notFound" to "Nenhum projeto encontrado.",
    "projects.deleteTitle" to "Apagar projeto",
    "projects.deleteQuestion" to "Tens a certeza que queres apagar",
    "projects.editTitle" to "Editar projeto",
    "projects.name" to "Nome",
    "projects.description" to "Descrição",
    "addProject.back" to "< Voltar aos Projetos",
    "addProject.title" to "Adicionar Novo Projeto",
    "addProject.name" to "Nome do Projeto",
    "addProject.namePlaceholder" to "Ex: Sistema CRM",
    "addProject.descriptionPlaceholder" to "Descreva os objetivos e âmbito do projeto...",
    "addProject.startDate" to "Data de Início",
    "addProject.endDate" to "Data de Fim (Prazo)",
    "addProject.manager" to "Gestor do Projeto",
    "addProject.managerPlaceholder" to "Selecione um gestor",
    "addProject.submit" to "Criar Projeto",
    "addTask.back" to "< Voltar às Tarefas",
    "addTask.title" to "Adicionar Nova Tarefa",
    "addTask.taskTitle" to "Título",
    "addTask.titlePlaceholder" to "Ex: Preparar documentação",
    "addTask.descriptionPlaceholder" to "Descreve o objetivo da tarefa...",
    "addTask.projectPlaceholder" to "Selecione um projeto",
    "addTask.submit" to "Criar Tarefa",
    "tasks.title" to "Todas as Tarefas",
    "tasks.subtitle" to "Tarefas organizadas por projeto",
    "tasks.add" to "Nova Tarefa",
    "tasks.search" to "Pesquisar por projeto ou tarefa...",
    "tasks.noProjects" to "Ainda não existem projetos para listar tarefas.",
    "tasks.visibleSummary" to "%1\$d visíveis · %2\$d pendentes · %3\$d completadas",
    "tasks.noMatching" to "Nenhuma tarefa corresponde aos filtros.",
    "tasks.deleteTitle" to "Eliminar tarefa",
    "tasks.deleteQuestion" to "Queres eliminar \"%1\$s\"?",
    "tasks.managementTitle" to "Gestão de Tarefas",
    "tasks.managementSubtitle" to "Cria tarefas e acompanha os responsáveis por projeto",
    "tasks.searchManager" to "Pesquisar tarefas...",
    "tasks.noFiltered" to "Não existem tarefas para os filtros selecionados.",
    "tasks.noVisible" to "Sem tarefas visíveis neste projeto.",
    "tasks.assignedTo" to "Associada a:",
    "tasks.noAssignees" to "Sem utilizadores associados.",
    "tasks.detailsAndObservations" to "Detalhes da tarefa e observações",
    "tasks.detailsTitle" to "Detalhes da tarefa",
    "tasks.observationsTitle" to "Observações da tarefa",
    "tasks.observationsSubtitle" to "Observações registadas pelos utilizadores associados",
    "tasks.observationDetail" to "Detalhe da observação",
    "tasks.observation" to "Observação",
    "tasks.timeSpent" to "Tempo gasto: %1\$s h",
    "tasks.groupSummary" to "%1\$d tarefas | %2\$d concluídas | %3\$d em progresso | %4\$d pendentes",
    "tasks.backObservations" to "< Voltar às Observações",
    "tasks.responsibles" to "Responsáveis",
    "tasks.records" to "Registos",
    "tasks.editTitle" to "Editar tarefa",
    "tasks.newTitle" to "Nova tarefa",
    "tasks.titleField" to "Título",
    "tasks.descriptionField" to "Descrição",
    "teams.title" to "Gestão de Equipas",
    "teams.subtitle" to "Administra utilizadores por função e projeto",
    "teams.totalUsers" to "Utilizadores totais",
    "teams.activeUsers" to "Utilizadores ativos",
    "teams.searchPlaceholder" to "Pesquisar por nome, username ou email...",
    "teams.role" to "Role",
    "teams.project" to "Projeto",
    "teams.removeTitle" to "Remover utilizador",
    "teams.removeQuestion" to "Tens a certeza que queres remover \"%1\$s\"? Esta ação elimina o acesso e os dados associados ao utilizador.",
    "teams.noMatching" to "Nenhum utilizador corresponde aos filtros.",
    "teams.remove" to "Remover",
    "manager.dashboard.title" to "Dashboard do gestor",
    "manager.dashboard.projects" to "Projetos do gestor",
    "manager.dashboard.projectsDetail" to "Projetos atribuídos ao gestor",
    "manager.dashboard.completedDetail" to "Tarefas finalizadas nos seus projetos",
    "manager.dashboard.progressDetail" to "Tarefas atualmente em desenvolvimento",
    "manager.projects.title" to "Meus Projetos",
    "manager.projects.subtitle" to "Acompanha projetos e equipa atribuída",
    "manager.projects.noFiltered" to "Não existem projetos para os filtros selecionados.",
    "manager.projects.detailsSubtitle" to "Detalhes, participantes, tarefas e observações",
    "manager.projects.detailsTitle" to "Detalhes do projeto",
    "manager.projects.notFoundTitle" to "Projeto não encontrado",
    "manager.projects.notFoundDetail" to "Não foi possível encontrar os detalhes deste projeto.",
    "manager.projects.noTasksTitle" to "Sem tarefas",
    "manager.projects.noTasksDetail" to "Este projeto ainda não tem tarefas registadas.",
    "manager.projects.participants" to "Participantes",
    "manager.projects.noParticipants" to "Sem participantes associados.",
    "manager.projects.tasksTotal" to "Total de tarefas: %1\$d",
    "manager.projects.back" to "< Voltar aos Projetos",
    "manager.projects.backProject" to "< Voltar ao Projeto",
    "manager.projects.projectTeam" to "Equipa do Projeto",
    "manager.projects.associate" to "Associar",
    "manager.projects.noMembers" to "Sem membros associados.",
    "manager.projects.completeTitle" to "Concluir projeto",
    "manager.projects.rateMembers" to "Avalia cada membro de 0 a 5 estrelas.",
    "manager.projects.noMembersToRate" to "Este projeto não tem membros para avaliar.",
    "manager.projects.associateUser" to "Associar utilizador",
    "manager.projects.noAvailableUsers" to "Não existem utilizadores disponíveis para associar.",
    "admin.projects.ratings" to "Classificações",
    "manager.team.title" to "Minha Equipa",
    "manager.team.subtitle" to "Utilizadores associados aos teus projetos",
    "manager.team.members" to "Membros",
    "manager.team.average" to "Média",
    "manager.team.completed" to "Concluídas",
    "manager.team.search" to "Pesquisar por nome, username, email ou projeto...",
    "manager.team.allProjects" to "Todos os projetos",
    "manager.team.noMembers" to "Nenhum membro encontrado.",
    "manager.team.noProjects" to "Sem projetos",
    "manager.team.ratingAverage" to "Média das estrelas",
    "manager.team.noRatings" to "Sem avaliações",
    "manager.team.completedTasks" to "Tarefas concluídas",
    "user.dashboard.title" to "Dashboard do utilizador",
    "user.dashboard.subtitle" to "Resumo das tuas tarefas atribuídas",
    "user.dashboard.progressDetail" to "Tarefas que já começaram",
    "user.dashboard.completedDetail" to "Tarefas finalizadas por ti",
    "user.dashboard.pendingDetail" to "Tarefas ainda por iniciar",
    "user.dashboard.lateDetail" to "Tarefas cujo prazo já passou",
    "user.tasks.title" to "Minhas Tarefas",
    "user.tasks.subtitle" to "Tarefas associadas ao teu utilizador",
    "user.tasks.back" to "< Voltar às tarefas",
    "user.tasks.notFoundTitle" to "Tarefa não encontrada",
    "user.tasks.notFoundDetail" to "Não foi possível encontrar esta tarefa nas tuas tarefas atribuídas.",
    "user.tasks.stateTitle" to "Estado das tarefas",
    "user.tasks.emptyTitle" to "Sem tarefas atribuídas",
    "user.tasks.emptyDetail" to "Quando uma tarefa for associada ao teu utilizador, ela aparece aqui.",
    "user.tasks.project" to "Projeto",
    "user.tasks.observations" to "Observações",
    "user.tasks.complete" to "Concluir",
    "user.tasks.completed" to "Concluída",
    "user.tasks.observationsTitle" to "Observações da tarefa",
    "user.tasks.addObservation" to "Adicionar observação",
    "user.tasks.noObservationsTitle" to "Sem observações",
    "user.tasks.noObservationsDetail" to "Ainda não existem observações nesta tarefa.",
    "user.tasks.observationText" to "Texto da observação",
    "user.tasks.addPhoto" to "Adicionar foto",
    "user.tasks.changePhoto" to "Alterar foto",
    "user.tasks.photoSelected" to "Foto selecionada",
    "user.tasks.completeTitle" to "Concluir tarefa",
    "user.tasks.completionDate" to "Data de conclusão",
    "user.tasks.datePlaceholder" to "AAAA-MM-DD",
    "user.tasks.completionLocation" to "Local de conclusão",
    "user.tasks.spentHours" to "Horas dispensadas",
    "user.tasks.hoursExample" to "Ex.: 2.5",
    "user.tasks.completion" to "Conclusão",
    "user.projects.title" to "Projetos Atribuídos",
    "user.projects.subtitle" to "Projetos associados ao teu utilizador",
    "user.projects.back" to "< Voltar aos projetos",
    "user.projects.notFoundTitle" to "Projeto não encontrado",
    "user.projects.notFoundDetail" to "Não foi possível encontrar este projeto nos teus projetos atribuídos.",
    "user.projects.stateTitle" to "Estado dos projetos",
    "user.projects.emptyTitle" to "Sem projetos atribuídos",
    "user.projects.emptyDetail" to "Quando fores associado a um projeto, ele aparece aqui.",
    "user.projects.tasks" to "Tarefas",
    "user.projects.late" to "Atrasadas",
    "user.projects.viewHistory" to "Ver histórico",
    "user.projects.historySubtitle" to "Histórico de tarefas concluídas neste projeto",
    "user.projects.noCompletedTitle" to "Sem tarefas concluídas",
    "user.projects.noCompletedDetail" to "Ainda não concluíste tarefas neste projeto.",
    "reports.adminTitle" to "Relatórios Executivos",
    "reports.adminSubtitle" to "Exporta estatísticas por utilizador, projeto ou tarefa.",
    "reports.managerTitle" to "Relatórios de Projeto",
    "reports.managerSubtitle" to "Exporta estatísticas dos teus projetos, equipa e tarefas.",
    "reports.availableExports" to "Exportações disponíveis",
    "reports.users" to "Utilizadores",
    "reports.projects" to "Projetos",
    "reports.tasks" to "Tarefas",
    "reports.team" to "Equipa",
    "reports.registeredHours" to "Horas registadas",
    "profile.title" to "A minha conta",
    "profile.subtitle" to "Informações básicas do teu perfil.",
    "profile.changeEmail" to "Alterar email",
    "profile.changePassword" to "Alterar palavra-passe",
    "profile.emailAssociated" to "Email associado",
    "profile.security" to "Segurança",
    "profile.currentEmail" to "Email atual: %1\$s",
    "profile.resendCode" to "Reenviar código",
    "profile.sending" to "A enviar...",
    "profile.sendCode" to "Enviar código para o email atual",
    "profile.receivedCode" to "Código recebido",
    "profile.newEmail" to "Novo email",
    "profile.oldPassword" to "Palavra-passe antiga",
    "profile.newPassword" to "Nova palavra-passe",
    "profile.confirmNewPassword" to "Confirmar nova palavra-passe",
    "profile.changeComplete" to "Alteração concluída",
    "profile.updatePasswordHint" to "Atualiza a tua palavra-passe de acesso.",
    "profile.deleteAccount" to "Eliminar conta",
    "profile.deleteHint" to "Esta ação remove a tua conta e termina a sessão.",
    "profile.deleteQuestion" to "Tens a certeza que queres eliminar a tua conta? Esta ação remove a conta do sistema e termina a sessão.",
    "profile.changePhoto" to "Alterar foto de perfil",
    "profile.removePhoto" to "Remover foto",
    "profile.photoDescription" to "Foto de perfil",
    "profile.deleting" to "A eliminar...",
    "profile.loadError" to "Não foi possível carregar a tua conta."
)

private val englishStrings = mapOf(
    "login.subtitle" to "Sign in",
    "login.password" to "Password",
    "login.submit" to "Sign in",
    "login.createAccount" to "Create account",
    "login.forgotPassword" to "Forgot password?",
    "login.resetTitle" to "Reset password",
    "login.resetDescription" to "Enter the email associated with your account and we will send you a recovery link.",
    "login.resetSend" to "Send email",
    "login.invalidEmail" to "Enter a valid email, for example name@email.com.",
    "login.invalidForm" to "Fill in your email and a password with at least 6 characters.",
    "register.subtitle" to "Create account",
    "register.name" to "Name",
    "register.password" to "Password",
    "register.submit" to "Register",
    "register.haveAccount" to "I already have an account",
    "register.invalidEmail" to "Enter a valid email, for example name@email.com.",
    "register.invalidForm" to "Fill in every field and use a password with at least 8 characters, letters and numbers.",
    "sidebar.projects" to "All Projects",
    "sidebar.tasks" to "All Tasks",
    "sidebar.teams" to "Team Management",
    "sidebar.reports" to "Executive Reports",
    "sidebar.settings" to "Global Settings",
    "sidebar.logout" to "Log out",
    "dashboard.state" to "Dashboard Status",
    "dashboard.error" to "Error",
    "dashboard.activeUsers" to "Active users",
    "dashboard.activeUsersDetail" to "Accounts with active status",
    "dashboard.completedProjects" to "Completed projects",
    "dashboard.completedProjectsDetail" to "Total finished projects",
    "dashboard.pendingProjects" to "Projects to finish",
    "dashboard.pendingProjectsDetail" to "Projects not finished yet",
    "settings.title" to "Global Settings",
    "settings.subtitle" to "Customize the app experience",
    "settings.preferences" to "Preferences",
    "settings.language" to "Language",
    "settings.languageDescription" to "Sets the main interface language.",
    "settings.theme" to "Theme",
    "settings.themeDescription" to "Chooses the dashboard appearance.",
    "settings.display" to "Display",
    "settings.dateFormat" to "Date format",
    "settings.dateFormatDescription" to "Example:",
    "settings.notifications" to "Notifications",
    "settings.notificationsDescription" to "Receive visual alerts from the app.",
    "settings.sounds" to "App sounds",
    "settings.soundsDescription" to "Enable sound feedback on main actions.",
    "settings.testNotification" to "Send test notification",
    "settings.testNotificationText" to "Notifications are active.",
    "settings.testSound" to "Test sound",
    "settings.footer" to "These preferences are saved on this device and load automatically when you open the app.",
    "theme.light" to "Light",
    "theme.dark" to "Dark",
    "theme.system" to "System",
    "common.search" to "Search",
    "common.all" to "All",
    "common.allFemale" to "All",
    "common.cancel" to "Cancel",
    "common.save" to "Save",
    "common.delete" to "Delete",
    "common.confirm" to "Confirm",
    "common.back" to "Back",
    "common.ok" to "OK",
    "common.retry" to "Try again",
    "common.moreInfo" to "More info",
    "common.exportCsv" to "Export CSV",
    "common.saving" to "Saving...",
    "common.creating" to "Creating...",
    "common.create" to "Create",
    "common.completing" to "Completing...",
    "common.start" to "Start",
    "common.end" to "End",
    "common.deadline" to "Deadline",
    "common.status" to "Status",
    "common.date" to "Date",
    "common.photos" to "Photos",
    "common.noPhotos" to "No photos",
    "common.photoEmpty" to "This observation has no attached photos.",
    "common.progress" to "Progress",
    "common.rows" to "rows",
    "common.users" to "Users",
    "common.user" to "User",
    "common.location" to "Location",
    "common.hours" to "Hours",
    "common.selectUser" to "Select a user",
    "common.noProjectUsers" to "This project does not have associated users yet.",
    "role.admin" to "Admin",
    "role.manager" to "Manager",
    "role.user" to "User",
    "common.noDescription" to "No description",
    "common.total" to "Total",
    "common.pending" to "Pending",
    "common.completed" to "Completed",
    "common.inProgress" to "In progress",
    "common.delayed" to "Delayed",
    "projects.title" to "All Projects",
    "projects.add" to "Add Project",
    "projects.list" to "Project List",
    "projects.search" to "Search projects...",
    "projects.notFound" to "No project found.",
    "projects.deleteTitle" to "Delete project",
    "projects.deleteQuestion" to "Are you sure you want to delete",
    "projects.editTitle" to "Edit project",
    "projects.name" to "Name",
    "projects.description" to "Description",
    "addProject.back" to "< Back to Projects",
    "addProject.title" to "Add New Project",
    "addProject.name" to "Project Name",
    "addProject.namePlaceholder" to "Ex: CRM System",
    "addProject.descriptionPlaceholder" to "Describe the project goals and scope...",
    "addProject.startDate" to "Start Date",
    "addProject.endDate" to "End Date",
    "addProject.manager" to "Project Manager",
    "addProject.managerPlaceholder" to "Select a manager",
    "addProject.submit" to "Create Project",
    "addTask.back" to "< Back to Tasks",
    "addTask.title" to "Add New Task",
    "addTask.taskTitle" to "Title",
    "addTask.titlePlaceholder" to "Ex: Prepare documentation",
    "addTask.descriptionPlaceholder" to "Describe the task objective...",
    "addTask.projectPlaceholder" to "Select a project",
    "addTask.submit" to "Create Task",
    "tasks.title" to "All Tasks",
    "tasks.subtitle" to "Tasks organized by project",
    "tasks.add" to "New Task",
    "tasks.search" to "Search by project or task...",
    "tasks.noProjects" to "There are no projects yet to list tasks.",
    "tasks.visibleSummary" to "%1\$d visible · %2\$d pending · %3\$d completed",
    "tasks.noMatching" to "No task matches the filters.",
    "tasks.deleteTitle" to "Delete task",
    "tasks.deleteQuestion" to "Do you want to delete \"%1\$s\"?",
    "tasks.managementTitle" to "Task Management",
    "tasks.managementSubtitle" to "Create tasks and track project assignees",
    "tasks.searchManager" to "Search tasks...",
    "tasks.noFiltered" to "There are no tasks for the selected filters.",
    "tasks.noVisible" to "No visible tasks in this project.",
    "tasks.assignedTo" to "Assigned to:",
    "tasks.noAssignees" to "No assigned users.",
    "tasks.detailsAndObservations" to "Task details and observations",
    "tasks.detailsTitle" to "Task details",
    "tasks.observationsTitle" to "Task observations",
    "tasks.observationsSubtitle" to "Observations registered by assigned users",
    "tasks.observationDetail" to "Observation detail",
    "tasks.observation" to "Observation",
    "tasks.timeSpent" to "Time spent: %1\$s h",
    "tasks.groupSummary" to "%1\$d tasks | %2\$d completed | %3\$d in progress | %4\$d pending",
    "tasks.backObservations" to "< Back to Observations",
    "tasks.responsibles" to "Assignees",
    "tasks.records" to "Records",
    "tasks.editTitle" to "Edit task",
    "tasks.newTitle" to "New task",
    "tasks.titleField" to "Title",
    "tasks.descriptionField" to "Description",
    "teams.title" to "Team Management",
    "teams.subtitle" to "Manage users by role and project",
    "teams.totalUsers" to "Total users",
    "teams.activeUsers" to "Active users",
    "teams.searchPlaceholder" to "Search by name, username or email...",
    "teams.role" to "Role",
    "teams.project" to "Project",
    "teams.removeTitle" to "Remove user",
    "teams.removeQuestion" to "Are you sure you want to remove \"%1\$s\"? This action deletes the user's access and associated data.",
    "teams.noMatching" to "No user matches the filters.",
    "teams.remove" to "Remove",
    "manager.dashboard.title" to "Manager Dashboard",
    "manager.dashboard.projects" to "Manager projects",
    "manager.dashboard.projectsDetail" to "Projects assigned to the manager",
    "manager.dashboard.completedDetail" to "Tasks finished in their projects",
    "manager.dashboard.progressDetail" to "Tasks currently in progress",
    "manager.projects.title" to "My Projects",
    "manager.projects.subtitle" to "Track projects and assigned team",
    "manager.projects.noFiltered" to "There are no projects for the selected filters.",
    "manager.projects.detailsSubtitle" to "Details, participants, tasks and observations",
    "manager.projects.detailsTitle" to "Project details",
    "manager.projects.notFoundTitle" to "Project not found",
    "manager.projects.notFoundDetail" to "Could not find this project's details.",
    "manager.projects.noTasksTitle" to "No tasks",
    "manager.projects.noTasksDetail" to "This project does not have registered tasks yet.",
    "manager.projects.participants" to "Participants",
    "manager.projects.noParticipants" to "No associated participants.",
    "manager.projects.tasksTotal" to "Total tasks: %1\$d",
    "manager.projects.back" to "< Back to Projects",
    "manager.projects.backProject" to "< Back to Project",
    "manager.projects.projectTeam" to "Project Team",
    "manager.projects.associate" to "Assign",
    "manager.projects.noMembers" to "No associated members.",
    "manager.projects.completeTitle" to "Complete project",
    "manager.projects.rateMembers" to "Rate each member from 0 to 5 stars.",
    "manager.projects.noMembersToRate" to "This project has no members to rate.",
    "manager.projects.associateUser" to "Assign user",
    "manager.projects.noAvailableUsers" to "There are no users available to assign.",
    "admin.projects.ratings" to "Ratings",
    "manager.team.title" to "My Team",
    "manager.team.subtitle" to "Users associated with your projects",
    "manager.team.members" to "Members",
    "manager.team.average" to "Average",
    "manager.team.completed" to "Completed",
    "manager.team.search" to "Search by name, username, email or project...",
    "manager.team.allProjects" to "All projects",
    "manager.team.noMembers" to "No member found.",
    "manager.team.noProjects" to "No projects",
    "manager.team.ratingAverage" to "Average rating",
    "manager.team.noRatings" to "No ratings",
    "manager.team.completedTasks" to "Completed tasks",
    "user.dashboard.title" to "User Dashboard",
    "user.dashboard.subtitle" to "Summary of your assigned tasks",
    "user.dashboard.progressDetail" to "Tasks that have already started",
    "user.dashboard.completedDetail" to "Tasks finished by you",
    "user.dashboard.pendingDetail" to "Tasks not started yet",
    "user.dashboard.lateDetail" to "Tasks whose deadline has passed",
    "user.tasks.title" to "My Tasks",
    "user.tasks.subtitle" to "Tasks associated with your user",
    "user.tasks.back" to "< Back to tasks",
    "user.tasks.notFoundTitle" to "Task not found",
    "user.tasks.notFoundDetail" to "Could not find this task in your assigned tasks.",
    "user.tasks.stateTitle" to "Task status",
    "user.tasks.emptyTitle" to "No assigned tasks",
    "user.tasks.emptyDetail" to "When a task is assigned to your user, it appears here.",
    "user.tasks.project" to "Project",
    "user.tasks.observations" to "Observations",
    "user.tasks.complete" to "Complete",
    "user.tasks.completed" to "Completed",
    "user.tasks.observationsTitle" to "Task observations",
    "user.tasks.addObservation" to "Add observation",
    "user.tasks.noObservationsTitle" to "No observations",
    "user.tasks.noObservationsDetail" to "There are no observations for this task yet.",
    "user.tasks.observationText" to "Observation text",
    "user.tasks.addPhoto" to "Add photo",
    "user.tasks.changePhoto" to "Change photo",
    "user.tasks.photoSelected" to "Photo selected",
    "user.tasks.completeTitle" to "Complete task",
    "user.tasks.completionDate" to "Completion date",
    "user.tasks.datePlaceholder" to "YYYY-MM-DD",
    "user.tasks.completionLocation" to "Completion location",
    "user.tasks.spentHours" to "Hours spent",
    "user.tasks.hoursExample" to "Ex.: 2.5",
    "user.tasks.completion" to "Completion",
    "user.projects.title" to "Assigned Projects",
    "user.projects.subtitle" to "Projects associated with your user",
    "user.projects.back" to "< Back to projects",
    "user.projects.notFoundTitle" to "Project not found",
    "user.projects.notFoundDetail" to "Could not find this project in your assigned projects.",
    "user.projects.stateTitle" to "Project status",
    "user.projects.emptyTitle" to "No assigned projects",
    "user.projects.emptyDetail" to "When you are associated with a project, it appears here.",
    "user.projects.tasks" to "Tasks",
    "user.projects.late" to "Late",
    "user.projects.viewHistory" to "View history",
    "user.projects.historySubtitle" to "History of completed tasks in this project",
    "user.projects.noCompletedTitle" to "No completed tasks",
    "user.projects.noCompletedDetail" to "You have not completed tasks in this project yet.",
    "reports.adminTitle" to "Executive Reports",
    "reports.adminSubtitle" to "Export statistics by user, project or task.",
    "reports.managerTitle" to "Project Reports",
    "reports.managerSubtitle" to "Export statistics for your projects, team and tasks.",
    "reports.availableExports" to "Available exports",
    "reports.users" to "Users",
    "reports.projects" to "Projects",
    "reports.tasks" to "Tasks",
    "reports.team" to "Team",
    "reports.registeredHours" to "Registered hours",
    "profile.title" to "My account",
    "profile.subtitle" to "Basic information about your profile.",
    "profile.changeEmail" to "Change email",
    "profile.changePassword" to "Change password",
    "profile.emailAssociated" to "Associated email",
    "profile.security" to "Security",
    "profile.currentEmail" to "Current email: %1\$s",
    "profile.resendCode" to "Resend code",
    "profile.sending" to "Sending...",
    "profile.sendCode" to "Send code to current email",
    "profile.receivedCode" to "Received code",
    "profile.newEmail" to "New email",
    "profile.oldPassword" to "Old password",
    "profile.newPassword" to "New password",
    "profile.confirmNewPassword" to "Confirm new password",
    "profile.changeComplete" to "Change completed",
    "profile.updatePasswordHint" to "Update your access password.",
    "profile.deleteAccount" to "Delete account",
    "profile.deleteHint" to "This action removes your account and logs you out.",
    "profile.deleteQuestion" to "Are you sure you want to delete your account? This action removes the account from the system and logs you out.",
    "profile.changePhoto" to "Change profile photo",
    "profile.removePhoto" to "Remove photo",
    "profile.photoDescription" to "Profile photo",
    "profile.deleting" to "Deleting...",
    "profile.loadError" to "Could not load your account."
)

private val spanishStrings = mapOf(
    "login.subtitle" to "Iniciar sesión",
    "login.password" to "Contraseña",
    "login.submit" to "Entrar",
    "login.createAccount" to "Crear cuenta",
    "login.forgotPassword" to "He olvidado mi contrasena",
    "login.resetTitle" to "Recuperar contrasena",
    "login.resetDescription" to "Introduce el email asociado a tu cuenta y te enviaremos un enlace de recuperacion.",
    "login.resetSend" to "Enviar email",
    "login.invalidEmail" to "Introduce un email válido, por ejemplo nombre@email.com.",
    "login.invalidForm" to "Rellena el email y una contraseña con al menos 6 caracteres.",
    "register.subtitle" to "Crear cuenta",
    "register.name" to "Nombre",
    "register.password" to "Contraseña",
    "register.submit" to "Registrar",
    "register.haveAccount" to "Ya tengo cuenta",
    "register.invalidEmail" to "Introduce un email válido, por ejemplo nombre@email.com.",
    "register.invalidForm" to "Rellena todos los campos y usa una contraseña con al menos 8 caracteres, letras y números.",
    "sidebar.dashboard" to "Panel",
    "sidebar.projects" to "Todos los Proyectos",
    "sidebar.tasks" to "Todas las Tareas",
    "sidebar.teams" to "Gestión de Equipos",
    "sidebar.reports" to "Informes Ejecutivos",
    "sidebar.settings" to "Ajustes Globales",
    "sidebar.logout" to "Salir",
    "dashboard.title" to "Panel Admin",
    "dashboard.state" to "Estado del panel",
    "dashboard.error" to "Error",
    "dashboard.activeUsers" to "Usuarios activos",
    "dashboard.activeUsersDetail" to "Cuentas con estado activo",
    "dashboard.completedProjects" to "Proyectos completados",
    "dashboard.completedProjectsDetail" to "Total de proyectos finalizados",
    "dashboard.pendingProjects" to "Proyectos por terminar",
    "dashboard.pendingProjectsDetail" to "Proyectos aún no finalizados",
    "settings.title" to "Ajustes Globales",
    "settings.subtitle" to "Personaliza la experiencia de la aplicación",
    "settings.preferences" to "Preferencias",
    "settings.language" to "Idioma",
    "settings.languageDescription" to "Define el idioma principal de la interfaz.",
    "settings.theme" to "Tema",
    "settings.themeDescription" to "Elige la apariencia general del panel.",
    "settings.display" to "Visualización",
    "settings.dateFormat" to "Formato de fecha",
    "settings.dateFormatDescription" to "Ejemplo:",
    "settings.notifications" to "Notificaciones",
    "settings.notificationsDescription" to "Recibe avisos visuales de la aplicación.",
    "settings.sounds" to "Sonidos de la aplicación",
    "settings.soundsDescription" to "Activa feedback sonoro en acciones principales.",
    "settings.testNotification" to "Enviar notificación de prueba",
    "settings.testNotificationText" to "Las notificaciones están activas.",
    "settings.testSound" to "Probar sonido",
    "settings.footer" to "Estas preferencias se guardan en este dispositivo y cargan automáticamente al abrir la app.",
    "theme.light" to "Claro",
    "theme.dark" to "Oscuro",
    "theme.system" to "Sistema",
    "common.search" to "Búsqueda",
    "common.all" to "Todos",
    "common.allFemale" to "Todas",
    "common.cancel" to "Cancelar",
    "common.save" to "Guardar",
    "common.delete" to "Eliminar",
    "common.confirm" to "Confirmar",
    "common.back" to "Volver",
    "common.ok" to "OK",
    "common.retry" to "Intentar de nuevo",
    "common.moreInfo" to "Más info",
    "common.exportCsv" to "Exportar CSV",
    "common.saving" to "Guardando...",
    "common.creating" to "Creando...",
    "common.create" to "Crear",
    "common.completing" to "Completando...",
    "common.start" to "Inicio",
    "common.end" to "Fin",
    "common.deadline" to "Plazo",
    "common.status" to "Estado",
    "common.date" to "Fecha",
    "common.photos" to "Fotos",
    "common.noPhotos" to "Sin fotos",
    "common.photoEmpty" to "Esta observación no tiene fotos adjuntas.",
    "common.progress" to "Progreso",
    "common.rows" to "filas",
    "common.users" to "Usuarios",
    "common.user" to "Usuario",
    "common.location" to "Lugar",
    "common.hours" to "Horas",
    "common.selectUser" to "Selecciona un usuario",
    "common.noProjectUsers" to "Este proyecto aún no tiene usuarios asociados.",
    "role.admin" to "Admin",
    "role.manager" to "Gestor",
    "role.user" to "Usuario",
    "common.noDescription" to "Sin descripción",
    "common.total" to "Total",
    "common.pending" to "Pendientes",
    "common.completed" to "Completadas",
    "common.inProgress" to "En progreso",
    "common.delayed" to "Atrasadas",
    "projects.title" to "Todos los Proyectos",
    "projects.add" to "Añadir Proyecto",
    "projects.list" to "Lista de Proyectos",
    "projects.search" to "Buscar proyectos...",
    "projects.notFound" to "Ningún proyecto encontrado.",
    "projects.deleteTitle" to "Eliminar proyecto",
    "projects.deleteQuestion" to "Seguro que quieres eliminar",
    "projects.editTitle" to "Editar proyecto",
    "projects.name" to "Nombre",
    "projects.description" to "Descripción",
    "addProject.back" to "< Volver a Proyectos",
    "addProject.title" to "Añadir Nuevo Proyecto",
    "addProject.name" to "Nombre del Proyecto",
    "addProject.namePlaceholder" to "Ej: Sistema CRM",
    "addProject.descriptionPlaceholder" to "Describe los objetivos y alcance del proyecto...",
    "addProject.startDate" to "Fecha de Inicio",
    "addProject.endDate" to "Fecha de Fin",
    "addProject.manager" to "Gestor del Proyecto",
    "addProject.managerPlaceholder" to "Selecciona un gestor",
    "addProject.submit" to "Crear Proyecto",
    "addTask.back" to "< Volver a Tareas",
    "addTask.title" to "Añadir Nueva Tarea",
    "addTask.taskTitle" to "Título",
    "addTask.titlePlaceholder" to "Ej: Preparar documentación",
    "addTask.descriptionPlaceholder" to "Describe el objetivo de la tarea...",
    "addTask.projectPlaceholder" to "Selecciona un proyecto",
    "addTask.submit" to "Crear Tarea",
    "tasks.title" to "Todas las Tareas",
    "tasks.subtitle" to "Tareas organizadas por proyecto",
    "tasks.add" to "Nueva Tarea",
    "tasks.search" to "Buscar por proyecto o tarea...",
    "tasks.noProjects" to "Todavía no hay proyectos para listar tareas.",
    "tasks.visibleSummary" to "%1\$d visibles · %2\$d pendientes · %3\$d completadas",
    "tasks.noMatching" to "Ninguna tarea corresponde a los filtros.",
    "tasks.deleteTitle" to "Eliminar tarea",
    "tasks.deleteQuestion" to "¿Quieres eliminar \"%1\$s\"?",
    "tasks.managementTitle" to "Gestión de Tareas",
    "tasks.managementSubtitle" to "Crea tareas y sigue los responsables por proyecto",
    "tasks.searchManager" to "Buscar tareas...",
    "tasks.noFiltered" to "No existen tareas para los filtros seleccionados.",
    "tasks.noVisible" to "Sin tareas visibles en este proyecto.",
    "tasks.assignedTo" to "Asignada a:",
    "tasks.noAssignees" to "Sin usuarios asociados.",
    "tasks.detailsAndObservations" to "Detalles de la tarea y observaciones",
    "tasks.detailsTitle" to "Detalles de la tarea",
    "tasks.observationsTitle" to "Observaciones de la tarea",
    "tasks.observationsSubtitle" to "Observaciones registradas por los usuarios asociados",
    "tasks.observationDetail" to "Detalle de la observación",
    "tasks.observation" to "Observación",
    "tasks.timeSpent" to "Tiempo dedicado: %1\$s h",
    "tasks.groupSummary" to "%1\$d tareas | %2\$d completadas | %3\$d en progreso | %4\$d pendientes",
    "tasks.backObservations" to "< Volver a Observaciones",
    "tasks.responsibles" to "Responsables",
    "tasks.records" to "Registros",
    "tasks.editTitle" to "Editar tarea",
    "tasks.newTitle" to "Nueva tarea",
    "tasks.titleField" to "Título",
    "tasks.descriptionField" to "Descripción",
    "teams.title" to "Gestión de Equipos",
    "teams.subtitle" to "Administra usuarios por rol y proyecto",
    "teams.totalUsers" to "Usuarios totales",
    "teams.activeUsers" to "Usuarios activos",
    "teams.searchPlaceholder" to "Buscar por nombre, username o email...",
    "teams.role" to "Rol",
    "teams.project" to "Proyecto",
    "teams.removeTitle" to "Eliminar usuario",
    "teams.removeQuestion" to "¿Seguro que quieres eliminar \"%1\$s\"? Esta acción elimina el acceso y los datos asociados al usuario.",
    "teams.noMatching" to "Ningún usuario corresponde a los filtros.",
    "teams.remove" to "Eliminar",
    "manager.dashboard.title" to "Panel del gestor",
    "manager.dashboard.projects" to "Proyectos del gestor",
    "manager.dashboard.projectsDetail" to "Proyectos asignados al gestor",
    "manager.dashboard.completedDetail" to "Tareas finalizadas en sus proyectos",
    "manager.dashboard.progressDetail" to "Tareas actualmente en desarrollo",
    "manager.projects.title" to "Mis Proyectos",
    "manager.projects.subtitle" to "Sigue proyectos y equipo asignado",
    "manager.projects.noFiltered" to "No existen proyectos para los filtros seleccionados.",
    "manager.projects.detailsSubtitle" to "Detalles, participantes, tareas y observaciones",
    "manager.projects.detailsTitle" to "Detalles del proyecto",
    "manager.projects.notFoundTitle" to "Proyecto no encontrado",
    "manager.projects.notFoundDetail" to "No fue posible encontrar los detalles de este proyecto.",
    "manager.projects.noTasksTitle" to "Sin tareas",
    "manager.projects.noTasksDetail" to "Este proyecto aún no tiene tareas registradas.",
    "manager.projects.participants" to "Participantes",
    "manager.projects.noParticipants" to "Sin participantes asociados.",
    "manager.projects.tasksTotal" to "Total de tareas: %1\$d",
    "manager.projects.back" to "< Volver a Proyectos",
    "manager.projects.backProject" to "< Volver al Proyecto",
    "manager.projects.projectTeam" to "Equipo del Proyecto",
    "manager.projects.associate" to "Asociar",
    "manager.projects.noMembers" to "Sin miembros asociados.",
    "manager.projects.completeTitle" to "Completar proyecto",
    "manager.projects.rateMembers" to "Valora cada miembro de 0 a 5 estrellas.",
    "manager.projects.noMembersToRate" to "Este proyecto no tiene miembros para valorar.",
    "manager.projects.associateUser" to "Asociar usuario",
    "manager.projects.noAvailableUsers" to "No existen usuarios disponibles para asociar.",
    "admin.projects.ratings" to "Clasificaciones",
    "manager.team.title" to "Mi Equipo",
    "manager.team.subtitle" to "Usuarios asociados a tus proyectos",
    "manager.team.members" to "Miembros",
    "manager.team.average" to "Media",
    "manager.team.completed" to "Completadas",
    "manager.team.search" to "Buscar por nombre, username, email o proyecto...",
    "manager.team.allProjects" to "Todos los proyectos",
    "manager.team.noMembers" to "Ningún miembro encontrado.",
    "manager.team.noProjects" to "Sin proyectos",
    "manager.team.ratingAverage" to "Media de estrellas",
    "manager.team.noRatings" to "Sin valoraciones",
    "manager.team.completedTasks" to "Tareas completadas",
    "user.dashboard.title" to "Panel del usuario",
    "user.dashboard.subtitle" to "Resumen de tus tareas asignadas",
    "user.dashboard.progressDetail" to "Tareas que ya han empezado",
    "user.dashboard.completedDetail" to "Tareas finalizadas por ti",
    "user.dashboard.pendingDetail" to "Tareas aún por iniciar",
    "user.dashboard.lateDetail" to "Tareas cuyo plazo ya pasó",
    "user.tasks.title" to "Mis Tareas",
    "user.tasks.subtitle" to "Tareas asociadas a tu usuario",
    "user.tasks.back" to "< Volver a tareas",
    "user.tasks.notFoundTitle" to "Tarea no encontrada",
    "user.tasks.notFoundDetail" to "No fue posible encontrar esta tarea en tus tareas asignadas.",
    "user.tasks.stateTitle" to "Estado de las tareas",
    "user.tasks.emptyTitle" to "Sin tareas asignadas",
    "user.tasks.emptyDetail" to "Cuando una tarea sea asociada a tu usuario, aparecerá aquí.",
    "user.tasks.project" to "Proyecto",
    "user.tasks.observations" to "Observaciones",
    "user.tasks.complete" to "Completar",
    "user.tasks.completed" to "Completada",
    "user.tasks.observationsTitle" to "Observaciones de la tarea",
    "user.tasks.addObservation" to "Añadir observación",
    "user.tasks.noObservationsTitle" to "Sin observaciones",
    "user.tasks.noObservationsDetail" to "Todavía no existen observaciones en esta tarea.",
    "user.tasks.observationText" to "Texto de la observación",
    "user.tasks.addPhoto" to "Añadir foto",
    "user.tasks.changePhoto" to "Cambiar foto",
    "user.tasks.photoSelected" to "Foto seleccionada",
    "user.tasks.completeTitle" to "Completar tarea",
    "user.tasks.completionDate" to "Fecha de conclusión",
    "user.tasks.datePlaceholder" to "AAAA-MM-DD",
    "user.tasks.completionLocation" to "Lugar de conclusión",
    "user.tasks.spentHours" to "Horas dedicadas",
    "user.tasks.hoursExample" to "Ej.: 2.5",
    "user.tasks.completion" to "Conclusión",
    "user.projects.title" to "Proyectos Asignados",
    "user.projects.subtitle" to "Proyectos asociados a tu usuario",
    "user.projects.back" to "< Volver a proyectos",
    "user.projects.notFoundTitle" to "Proyecto no encontrado",
    "user.projects.notFoundDetail" to "No fue posible encontrar este proyecto en tus proyectos asignados.",
    "user.projects.stateTitle" to "Estado de los proyectos",
    "user.projects.emptyTitle" to "Sin proyectos asignados",
    "user.projects.emptyDetail" to "Cuando estés asociado a un proyecto, aparecerá aquí.",
    "user.projects.tasks" to "Tareas",
    "user.projects.late" to "Atrasadas",
    "user.projects.viewHistory" to "Ver historial",
    "user.projects.historySubtitle" to "Historial de tareas completadas en este proyecto",
    "user.projects.noCompletedTitle" to "Sin tareas completadas",
    "user.projects.noCompletedDetail" to "Todavía no has completado tareas en este proyecto.",
    "reports.adminTitle" to "Informes Ejecutivos",
    "reports.adminSubtitle" to "Exporta estadísticas por usuario, proyecto o tarea.",
    "reports.managerTitle" to "Informes de Proyecto",
    "reports.managerSubtitle" to "Exporta estadísticas de tus proyectos, equipo y tareas.",
    "reports.availableExports" to "Exportaciones disponibles",
    "reports.users" to "Usuarios",
    "reports.projects" to "Proyectos",
    "reports.tasks" to "Tareas",
    "reports.team" to "Equipo",
    "reports.registeredHours" to "Horas registradas",
    "profile.title" to "Mi cuenta",
    "profile.subtitle" to "Información básica de tu perfil.",
    "profile.changeEmail" to "Cambiar email",
    "profile.changePassword" to "Cambiar contraseña",
    "profile.emailAssociated" to "Email asociado",
    "profile.security" to "Seguridad",
    "profile.currentEmail" to "Email actual: %1\$s",
    "profile.resendCode" to "Reenviar código",
    "profile.sending" to "Enviando...",
    "profile.sendCode" to "Enviar código al email actual",
    "profile.receivedCode" to "Código recibido",
    "profile.newEmail" to "Nuevo email",
    "profile.oldPassword" to "Contraseña antigua",
    "profile.newPassword" to "Nueva contraseña",
    "profile.confirmNewPassword" to "Confirmar nueva contraseña",
    "profile.changeComplete" to "Cambio completado",
    "profile.updatePasswordHint" to "Actualiza tu contraseña de acceso.",
    "profile.deleteAccount" to "Eliminar cuenta",
    "profile.deleteHint" to "Esta acción elimina tu cuenta y cierra la sesión.",
    "profile.deleteQuestion" to "¿Seguro que quieres eliminar tu cuenta? Esta acción elimina la cuenta del sistema y cierra la sesión.",
    "profile.changePhoto" to "Cambiar foto de perfil",
    "profile.removePhoto" to "Eliminar foto",
    "profile.photoDescription" to "Foto de perfil",
    "profile.deleting" to "Eliminando...",
    "profile.loadError" to "No fue posible cargar tu cuenta."
)
