-- Account notifications shown in the ProjectHub top bar.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  title text not null,
  message text not null,
  type text not null default 'INFO',
  related_route text,
  related_entity_id integer,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx
on public.notifications (user_id, created_at desc);

create index if not exists notifications_user_unread_idx
on public.notifications (user_id, is_read)
where is_read = false;

alter table public.notifications enable row level security;

drop policy if exists "Users can read own notifications" on public.notifications;
drop policy if exists "Users can update own notifications" on public.notifications;
drop policy if exists "Admins can manage notifications" on public.notifications;
drop policy if exists "Managers can create notifications" on public.notifications;

create policy "Users can read own notifications"
on public.notifications
for select
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.id = notifications.user_id
      and u.email = auth.jwt() ->> 'email'
  )
);

create policy "Users can update own notifications"
on public.notifications
for update
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.id = notifications.user_id
      and u.email = auth.jwt() ->> 'email'
  )
)
with check (
  exists (
    select 1
    from public.users u
    where u.id = notifications.user_id
      and u.email = auth.jwt() ->> 'email'
  )
);

create policy "Admins can manage notifications"
on public.notifications
for all
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.email = auth.jwt() ->> 'email'
      and upper(u.role) = 'ADMIN'
  )
)
with check (
  exists (
    select 1
    from public.users u
    where u.email = auth.jwt() ->> 'email'
      and upper(u.role) = 'ADMIN'
  )
);

create policy "Managers can create notifications"
on public.notifications
for insert
to authenticated
with check (
  exists (
    select 1
    from public.users u
    where u.email = auth.jwt() ->> 'email'
      and upper(u.role) in ('ADMIN', 'GESTOR')
  )
);

create or replace function public.prevent_notification_content_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_role text;
begin
  select upper(u.role)
  into current_role
  from public.users u
  where u.email = auth.jwt() ->> 'email'
  limit 1;

  if current_role = 'ADMIN' then
    return new;
  end if;

  if old.user_id is distinct from new.user_id
    or old.title is distinct from new.title
    or old.message is distinct from new.message
    or old.type is distinct from new.type
    or old.related_route is distinct from new.related_route
    or old.related_entity_id is distinct from new.related_entity_id
    or old.created_at is distinct from new.created_at then
    raise exception 'Only notification read state can be updated';
  end if;

  return new;
end;
$$;

drop trigger if exists prevent_notification_content_update_trigger on public.notifications;

create trigger prevent_notification_content_update_trigger
before update on public.notifications
for each row
execute function public.prevent_notification_content_update();
